#### Nama :  Sylva Flowrends
#### NPM : 51420230
#### Kelas : 3IA16
#### M8 Rekayasa Komputasional (Vclass)

In [1]:
import numpy as np

In [8]:
matriks1 = np.array([[5,1], [4,2]])
matriks2 = np.array([[0,2], [3,0]])

tambah_m = matriks1 + matriks2
kurang_m = matriks1 - matriks2
p_skalar = np.dot(matriks1, matriks2)

print("Hasil penambahan matriks  : \n",tambah_m)
print("\n")
print("Hasil pengurangan matriks : \n",kurang_m)
print("\n")
print("Hasil perkalian skalar matriks: \n",p_skalar)

Hasil penambahan matriks  : 
 [[5 3]
 [7 2]]


Hasil pengurangan matriks : 
 [[ 5 -1]
 [ 1  2]]


Hasil perkalian skalar matriks: 
 [[ 3 10]
 [ 6  8]]
